ALTER TABLE users ADD COLUMN user_provide_uid VARCHAR(255) NULL;
ALTER TABLE users ADD COLUMN email_verified BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN provider VARCHAR(255) NULL;
ALTER TABLE users ADD COLUMN method VARCHAR(255) NULL;
