services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq-bytehub'
    environment:
      - 'RABBITMQ_DEFAULT_USER=admin'
      - 'RABBITMQ_DEFAULT_PASS=admin'
    #      - RABBITMQ_DEFAULT_VHOST=/
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_bytehub
networks:
  rabbitmq_bytehub:
    driver: bridge
