#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️ Styling, testing and building your portfolio before committing.'

# Check Prettier standards
echo '🎨 Prettifying your code.'
npm run check-format ||
(
    echo '❌ 🎨 Prettier Check Failed. Run npm run format, add changes and try committing again. 🎨 ❌';
    exit 1;
)

#echo '🤵 Checking ESLint standards.'
## Check ESLint Standards
#npm run check-lint ||
#(
#    echo '🤵 ❌ ESLint Check Failed. Make the changes required above and try committing again. ❌ 🤵';
#    exit 1;
#)

echo '⌨️ Type checking.'
# Check tsconfig standards
npm run check-types ||
(
    echo '❌ ⌨️ Failed Type check. Make the changes required above and try committing again. ⌨️ ❌';
    exit 1;
)

# If everything passes... Now we can commit
echo '✅ ✅ Your checked-in code looks good. Committing... ✅ ✅'
